"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$nats\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$fill\
$pijul_channel\
$docker_context\
$package\
$bun\
$c\
$cmake\
$cobol\
$cpp\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$maven\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$guix_shell\
$nix_shell\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$container\
$netns\
$os\
$shell\
$character"""

[time]
format = ' [ $time]($style)'
disabled = false

[cmd_duration]
format = ' [ $duration]($style)'

[fill]
symbol = "·"

[aws]
symbol = " "

[azure]
symbol = " "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[buf]
symbol = " "

[bun]
symbol = " "
format = ' [$symbol($version)]($style)'

[c]
symbol = " "
format = ' [$symbol($version(-$name))]($style)'

[cpp]
symbol = " "
format = ' [$symbol($version(-$name))]($style)'

[cmake]
symbol = " "

[cobol]
symbol = " "

[conda]
symbol = " "

[container]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "
format = ' [$symbol($version)]($style)'

[deno]
symbol = " "
format = ' [$symbol($version)]($style)'

[direnv]
symbol = " "

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
truncation_length = 8
truncate_to_repo = false
truncation_symbol = '…/'
read_only = " 󰌾"

[docker_context]
symbol = " "

[dotnet]
symbol = " "
format = ' [$symbol($version)]($style)'

[elixir]
symbol = " "
format = ' [$symbol($version)]($style)'

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "󱇶 "

[gleam]
symbol = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
only_attached = true
truncation_length = 32

[git_commit]
commit_hash_length = 8
format = '([$tag ]($style))[ $hash]($style) '
tag_disabled = false
tag_symbol = ' '

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
rebase = 'rebase'
merge = 'merge'
revert = 'revert'
cherry_pick = 'cherry-pick'
bisect = 'bisect'
am = 'am'
am_or_rebase = 'am/rebase'

[git_status]
format = '([$ahead_behind$stashed$conflicted$staged$modified$untracked]($style))'
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇣${behind_count}⇡${ahead_count} '
stashed = '*${count} '
conflicted = '~${count} '
staged = '+${count} '
modified = '!${count} '
untracked = '?${count} '

[golang]
symbol = " "
format = ' [$symbol($version)( $mod_version)]($style)'

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = ' [$symbol($version)]($style)'

[julia]
symbol = " "
format = ' [$symbol($version)]($style)'

[kotlin]
symbol = " "
format = ' [$symbol($version)]($style)'

[kubernetes]
symbol = "󱃾 "

[lua]
symbol = " "
format = ' [$symbol($version)]($style)'

[maven]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[mojo]
symbol = "󰈸 "

[nats]
symbol = " "

[netns]
symbol = "󰛳 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = ' [$symbol($version)]($style)'

[ocaml]
symbol = " "

[odin]
symbol = "󰟢 "

[opa]
symbol = " "

[openstack]
symbol = " "

[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "
format = ' [$symbol($version)]($style)'

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "
format = ' [$symbol${pyenv_prefix}(${version})( \($virtualenv\))]($style)'

[raku]
symbol = "󱖊 "

[red]
symbol = "󱍼 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
format = ' [$symbol($version)]($style)'

[rust]
symbol = "󱘗 "
format = ' [$symbol($version)]($style)'

[scala]
symbol = " "

[shlvl]
symbol = "󰹍 "

[singularity]
symbol = " "

[solidity]
symbol = " "

[spack]
symbol = " "

[status]
symbol = " "

[sudo]
symbol = " "

[swift]
symbol = " "
format = ' [$symbol($version)]($style)'

[terraform]
symbol = " "

[vlang]
symbol = " "

[typst]
symbol = " "

[vagrant]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
